name: Workflow 001
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Vinod Shalagar Here!"
      - run: ls -1
      - uses: actions/checkout@v2
      - run: ls -1
      

