name: Workflow 001 ( this appears left pane)
on:
  workflow_dispatch:

jobs:
  greet:
    env:
        MY_ENV: "vinod shalgar"
        FNAME: "VINOD"
        LNAME: "SHALGAR"
        MNAME: "N"
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Vinod Shalagar Here!"
      
      - run: ls -1
      - uses: actions/checkout@v3
      - run: ls -1
      - run: echo "shalgar vinod"
      - run: echo "rajshree shalgar"
      - name: run multi-line script
        run: |
          echo "my name is $MY_ENV"
          echo "tsting multiple name is $MY_ENV"
          echo "tsting multiple name1 is $MY_ENV"
          echo "tsting multiple name is $GITHUB_ACTOR"
          echo "my full  name is $FNAME$MNAME$LNAME"
      

