name: Workflow 001 ( this appears left pane)
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Vinod Shalagar Here!"
      
      - run: ls -1
      # - uses: actions/checkout@v3
      - run: ls -1
      - run: echo "shalgar vinod"
      - run: echo "rajshree shalgar"
      

